"""LinkedIn outreach: 30 high-fit YC S2026 companies (batch 1: 20, batch 2: 10).

Two messages per contact: a connection note (at most 200 characters, the
limit for personalised invites on free accounts) and a DM to send once they
accept, with a subject line for when it goes out as InMail. Both cite real,
sourced facts about the company (see research/source) to show homework. Run to validate
lengths and write docs/linkedin-outreach-day-1.md and private/linkedin-tracker.csv.
"""
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTE_LIMIT = 200

# LinkedIn profiles found via web search (September 2026). "Verified": the
# profile headline names the company. "Check": matched from a post URL or the
# headline differs, so glance at the profile before sending.
LEADS = [
    # --- GTM & growth builders ---
    dict(company='LemonLime', category='GTM & growth builders', contact='Daniela Muñoz', backup='Jordan Zietz',
         linkedin='https://www.linkedin.com/in/danielamunoz12/', status='Verified', batch=1,
         subject="A data layer for LemonLime's agents",
         research="Connects to a business's existing tools and self-creates specialized AI agents and automations in minutes, no code.",
         source='https://www.linkedin.com/in/danielamunoz12/',
         note="Hi Daniela, saw LemonLime spins up custom AI agents from a business's existing tools in minutes, no code. Love that. Arsham from SpringBrand here. Would love to connect!",
         dm="Thanks for connecting, Daniela!\n\nSince LemonLime builds agents that run a small business's GTM, the hard part is feeding them good data. SpringBrand gives agents lead lists, competitor traffic, social listening and content generation through one connection, at under a cent per call with no subscription.\n\nHappy to load free credits so you can test it inside one of the agents LemonLime creates. Worth a try?"),
    dict(company='Nex', category='GTM & growth builders', contact='Nazz Mohammad', backup='Francisco Dias',
         linkedin='https://www.linkedin.com/in/najmuzzaman/', status='Verified', batch=1,
         subject='The GTM data under Nex',
         research='#1 Product of the Day on Product Hunt (Sep 3, 2026); audited 1000s of HubSpot records on one onboarding call; ex-HubSpot team backed by Dharmesh Shah.',
         source='https://x.com/najmuzzaman/status/2089473930377777393',
         note='Hi Nazz, congrats on #1 Product of the Day! Nex auditing thousands of HubSpot records on a single onboarding call is wild. Arsham from SpringBrand here. Would love to connect.',
         dm="Thanks for connecting, Nazz!\n\nList qualification and revenue recovery at Nex's volume need fresh data behind them. SpringBrand gives agents company and contact discovery, traffic and SEO research and social signals per call, typically under a cent, with no subscription.\n\nIt could be a data source your agents call mid-workflow. Want free credits to test it on one list-qualification run?"),
    dict(company='TryNearby', category='GTM & growth builders', contact='Obaida Albaroudi', backup='Ahmad Ibrahim',
         linkedin='https://www.linkedin.com/in/obaida-albaroudi-b7b366279/', status="Check: taken from one of Obaida's TryNearby posts", batch=1,
         subject='Local creators for your next city',
         research='Live with 120+ paying restaurants across Southern California; 90%+ customer retention; Obaida was an early Replit employee.',
         source='https://www.linkedin.com/posts/obaida-albaroudi-b7b366279_11-restaurants-in-24-hours-spanning-san-activity-7500633711164469248-tJXp',
         note='Hi Obaida, 120+ paying restaurants across SoCal with 90%+ retention is a great start for TryNearby. Arsham from SpringBrand here. We help agents find creators. Would love to connect!',
         dm="Thanks for connecting, Obaida!\n\nScaling past Southern California means finding good local creators in every new city, fast. SpringBrand's AI tools find creators on TikTok, Instagram and YouTube by city and niche, plus restaurants to pitch, at under a cent per call.\n\nWhich city are you expanding to next? I'll send you a free list of local food creators there."),
    dict(company='Osmaura', category='GTM & growth builders', contact='Jity Woldemichael', backup='Kali Abeje',
         linkedin='https://www.linkedin.com/in/tselote/', status='Verified', batch=1,
         subject="Where your law firms' rivals get clients",
         research='Went from $0 to $144K annualized run rate in one month; agents monitor legal-specific data sources to spot demand and run outreach; MIT founders.',
         source='https://www.linkedin.com/posts/tselote_im-excited-to-share-that-osmaura-yc-s26-activity-7475947824581529600-j5BM',
         note="Hi Jity, $0 to $144K run rate in a month is huge. Love how Osmaura's agents spot demand for a firm's expertise. Arsham from SpringBrand here. Would love to connect!",
         dm="Thanks for connecting, Jity!\n\nOsmaura's agents already find demand signals for law firms. SpringBrand could add more fuel: traffic data on rival firms, keyword gaps and social listening, all callable by your agents at under a cent per call, with no subscription.\n\nWant free credits to test it on one of your client firms' markets?"),
    dict(company='Grocalo', category='GTM & growth builders', contact='David Hwang', backup='Alex Yee',
         linkedin='https://www.linkedin.com/in/david-hwang-b5301436/', status='Verified', batch=2,
         subject="Trends and creators for Grocalo's next clients",
         research='Generated 2B views and 4M followers for creators in 2 months; clients include King Bach, Steven He, Jimmy O. Yang and Jeannie Mai; co-founder Alex Yee built and sold Onederful (YC W18).',
         source='https://www.ycombinator.com/launches/Sxb-grocalo-ai-brain-that-runs-content-for-creators',
         note='Hi David, 2B views and 4M followers for creators like King Bach and Steven He in two months is wild. Arsham from SpringBrand here. Would love to connect!',
         dm="Thanks for connecting, David!\n\nGrocalo already runs content for some of the biggest creators out there. SpringBrand could plug into that engine: trend tracking across TikTok, Instagram, YouTube and RedNote, creator discovery for your next clients, and video and voiceover generation, all per call at under a cent, with no subscription.\n\nWant free credits to test it on one creator's content pipeline?"),
    dict(company='Chromie', category='GTM & growth builders', contact='Akshay Mistry', backup='Ananth Sankaralingam',
         linkedin='https://www.linkedin.com/in/akshaymistry-/', status='Verified', batch=2,
         subject='Contractors who should be on Chromie',
         research='AI operating system for government contracting; surfaces agency signals and expiring contracts months before the RFP; supports contractors with 100+ prime awards and $250M+ obligated value; customers 3x their proposal output; founders ex-Google, LinkedIn, Plaid and Amazon.',
         source='https://www.chromie.dev/',
         note='Hi Akshay, surfacing expiring contracts months before the RFP drops is a real edge, and $250M+ in obligated value already is impressive. Arsham, SpringBrand. Would love to connect!',
         dm="Thanks for connecting, Akshay!\n\nChromie's buyers are government contractors, a crowd that's hard to find by job title alone. SpringBrand's AI tools can build lists of contracting firms by sector and size, with their BD and capture leads, and push them into your CRM. Calls are under a cent, with no subscription.\n\nWant a free list of 25 contractors that look like your best customers?"),
    # --- AI agent infra & devtools ---
    dict(company='HyperProbe', category='AI agent infra & devtools', contact='Shailendra Singh', backup='Karan Raina',
         linkedin='https://www.linkedin.com/in/shailendra-singh-6540b8b/', status='Verified', batch=1,
         subject="Who's talking about prod debugging this week",
         research='Captures live variable state when a probe fires, under 1% CPU overhead, automatic PII redaction; Shailendra previously founded HyperTest.',
         source='https://www.linkedin.com/in/shailendra-singh-6540b8b/',
         note='Hi Shailendra, live variable state at under 1% CPU overhead is a strong answer to agents guessing from logs. Second company after HyperTest too! Arsham, SpringBrand. Would love to connect.',
         dm="Thanks for connecting, Shailendra!\n\nWinning on-call and SRE teams mostly happens in X, Reddit and Hacker News threads about incidents. SpringBrand plugs GTM tools into Claude Code or Cursor: who's discussing AI debugging right now, where competing tools get their traffic, and which teams fit your ideal customer. Most calls cost under a cent.\n\nCan I send you a free snapshot of this week's conversations?"),
    dict(company='Agnost AI', category='AI agent infra & devtools', contact='Parth Ajmera', backup='Shubham Palriwala',
         linkedin='https://www.linkedin.com/in/parthajmera/', status='Verified', batch=1,
         subject="Who's discussing agent analytics right now",
         research='Helps conversational AI companies see why users churn by reading every conversation; Parth is ex-Cisco and Microsoft, IIT Madras; went through Entrepreneurs First.',
         source='https://www.linkedin.com/in/parthajmera',
         note='Hi Parth, reading every agent conversation to find out why users churn is such a clear pitch. From EF to YC S26, congrats! Arsham from SpringBrand here. Would love to connect.',
         dm="Thanks for connecting, Parth!\n\nAgnost's buyers are conversational AI teams, and SpringBrand can help you find them: companies shipping chat and voice agents with the right product leads, plus who's discussing agent churn on X and Reddit. It runs inside Claude Code or Cursor at under a cent per call.\n\nWant a free list of 25 conversational AI companies to start?"),
    dict(company='Mentlio', category='AI agent infra & devtools', contact='Ashank Shah', backup='Ahmet Demirbas',
         linkedin='https://www.linkedin.com/in/ashank-shah/', status='Verified', batch=1,
         subject='25 AI coding teams that fit Mentlio',
         research='Cuts ~30% of AI spend via routing, context optimization and prompt compression, without collecting prompts or source code; Caltech founders.',
         source='https://www.mentlio.com/',
         note='Hi Ashank, cutting ~30% of AI coding spend without ever touching prompts or source code is a smart line. Arsham from SpringBrand here. Would love to connect!',
         dm="Thanks for connecting, Ashank!\n\nMentlio sells to engineering leaders watching their AI bills climb. SpringBrand's AI tools can find companies with large engineering teams and their VP Eng or CTO, and track the Reddit and X threads where devs vent about token costs. Calls are under a cent, with no subscription.\n\nWant a free list of 25 teams that match Mentlio's ideal customer?"),
    dict(company='Conifer', category='AI agent infra & devtools', contact='Michael Jeffords', backup='Charles Muehlberger',
         linkedin='https://www.linkedin.com/in/michael-bryan-jeffords/', status='Verified', batch=1,
         subject="This week's token-bill complaints, free",
         research='Inference engine built in Rust, decode up to 60% faster than llama.cpp; routes each request to the cheapest capable model, local first.',
         source='https://www.linkedin.com/in/michael-bryan-jeffords/',
         note='Hi Michael, a Rust inference engine decoding up to 60% faster than llama.cpp is impressive work. Arsham from SpringBrand here. Would love to connect!',
         dm="Thanks for connecting, Michael!\n\nWe're pay per call too, so Conifer's cost story resonates. SpringBrand runs GTM tools inside your coding agent: it can find the Reddit and X threads where devs complain about token bills and local-model setups, and see where competing routers get their traffic. Typical calls cost under a cent.\n\nWant me to pull this week's threads for you, free?"),
    dict(company='Agent FM', category='AI agent infra & devtools', contact='Mugdhaa Patankar', backup='Aniket Deshpande',
         linkedin='https://www.linkedin.com/in/mugdhaa-patankar/', status='Verified', batch=2,
         subject='Where devs talk about running agent fleets',
         research='Desktop app where coding agents post progress, blockers and decisions to one group chat, with live text and audio updates on Mac and Windows; Mugdhaa led AI for developer productivity at Snowflake (also Twitch, AWS).',
         source='https://www.linkedin.com/in/mugdhaa-patankar/',
         note='Hi Mugdhaa, one group chat with live audio updates from your coding agents is a fun take, and it builds on your dev-productivity work at Snowflake. Arsham, SpringBrand. Would love to connect!',
         dm="Thanks for connecting, Mugdhaa!\n\nEngineers running several coding agents at once are exactly who Agent FM is for, and they talk about it on X and Reddit. SpringBrand plugs GTM tools into Claude Code or Cursor: find those threads, see where competing tools get their traffic, and find eng teams that fit. Most calls cost under a cent.\n\nCan I send you a free snapshot of this week's conversations?"),
    # --- B2B / enterprise AI SaaS ---
    dict(company='Litmus', category='B2B / enterprise AI SaaS', contact='Elena Zhao', backup='Shaivi Rau',
         linkedin='https://www.linkedin.com/in/elena-zhao-015353217/', status='Verified', batch=1,
         subject='25 companies hiring engineers right now',
         research='First sale to $60K ARR in a month; 3,000+ assessments; trials generated from real codebases and tickets; customers include Composio and Neo Scholars.',
         source='https://www.linkedin.com/in/elena-zhao-015353217/',
         note="Hi Elena, first sale to $60K ARR in a month, with trials built from a company's real codebase. Litmus is sharp. Arsham from SpringBrand here. Would love to connect!",
         dm="Thanks for connecting, Elena!\n\nLitmus works best for teams actively hiring engineers, like Composio. SpringBrand's AI tools can find more of them: startups with open engineering roles right now, with the founder or head of engineering, pushed into your CRM. It's under a cent per typical call, all on one bill.\n\nWant a free list of 25 companies hiring engineers this week?"),
    dict(company='Rence', category='B2B / enterprise AI SaaS', contact='Frans Paborn', backup='Jonas Rosengren',
         linkedin='https://www.linkedin.com/in/frans-paborn-990120305/', status='Verified', batch=1,
         subject='25 field sales teams for Rence',
         research='Reps record visits and get coached in minutes; scores every meeting against the playbook and writes the follow-up to the CRM. Listed as YC F26 (not S26).',
         source='https://www.rence.ai/',
         note='Hi Frans, scoring every field visit against the playbook and writing the follow-up to the CRM is a smart loop. Arsham from SpringBrand here. Would love to connect!',
         dm="Thanks for connecting, Frans!\n\nRence's buyers run in-person sales teams in solar, home improvement, retail and field services. SpringBrand's AI tools can find those companies and their sales leaders across Europe and the US, and add them to your CRM, at under a cent per call.\n\nWant a free sample of 25 field-sales companies to start with?"),
    dict(company='Poth Labs', category='B2B / enterprise AI SaaS', contact='Matthew Wong', backup='Mojmír Horváth',
         linkedin='https://www.linkedin.com/in/matthew-wong-b56180277/', status="Check: headline still shows Palantir, but Matthew's Poth launch posts come from this profile", batch=2,
         subject='Teams asking why their users churn',
         research='Unifies analytics, call transcripts, support tickets, surveys and CRM notes into a model of the customer, then tests hypotheses with adaptive interviews; Matthew was a forward-deployed engineer at Palantir.',
         source='https://yespress.io/poth-labs-yc-s26',
         note='Hi Matthew, turning scattered analytics, tickets and CRM notes into tested hypotheses on why users churn is a sharp idea. Arsham from SpringBrand. Would love to connect!',
         dm="Thanks for connecting, Matthew!\n\nPoth's buyers are product and growth teams who know what users did but not why. SpringBrand's AI tools can find those teams at companies that fit your ideal customer, pull their product leads into your CRM, and track who's discussing churn and activation on X and Reddit. Calls are under a cent.\n\nWant a free list of 25 companies that fit?"),
    # --- Vertical AI for SMBs ---
    dict(company='CarSignal', category='Vertical AI for SMBs', contact='Michael Muzzin', backup='Junaid Popalzai',
         linkedin='https://www.linkedin.com/in/mmuzzin/', status='Verified', batch=1,
         subject='Every auto shop in one city',
         research="AI-powered scan tool that plugs into the car; replaces the disjointed software used by 300,000+ US shops; founders' families have 50+ years in the auto industry.",
         source='https://www.linkedin.com/in/mmuzzin/',
         note='Hi Michael, an AI scan tool that plugs straight into the car is a great wedge into 300K+ US shops. Love the family auto roots too. Arsham, SpringBrand. Would love to connect!',
         dm="Thanks for connecting, Michael!\n\nWith 300,000+ shops to reach, CarSignal's growth is a list-building game. SpringBrand's AI tools build lists of independent auto repair shops by city with owner contacts, find the local keywords shops search, and make short demo videos of the scan tool in action. Most calls cost under a cent.\n\nPick a city and I'll send you a free list. Where should I start?"),
    dict(company='Marble', category='Vertical AI for SMBs', contact='Aakar Khanna', backup='Arjun Chaliha',
         linkedin='https://www.linkedin.com/in/aakarkhanna/', status="Check: headline says Truffle (YC S26), possibly Marble's new name", batch=1,
         subject='50 NYC restaurant groups to test with',
         research='Computer vision counts inventory 90% faster; 97% item-level forecast accuracy; 40%+ less food waste; Aakar grew up running family restaurants and covered restaurants at Goldman. LinkedIn headline says Truffle (YC S26), so the name may have changed: messages avoid the company name.',
         source='https://www.linkedin.com/in/aakarkhanna/',
         note='Hi Aakar, counting inventory 90% faster with computer vision and cutting food waste 40%+ is a big deal for restaurants. Arsham from SpringBrand here. Would love to connect!',
         dm="Thanks for connecting, Aakar!\n\nAfter growing up in your family's restaurants and covering the sector at Goldman, you know how hard operators are to reach. SpringBrand's AI tools build lists of independent and multi-unit restaurants by city with owner contacts, and make short demo videos for Instagram. Calls are under a cent, with no subscription.\n\nWant a free list of 50 NYC multi-unit operators to test with?"),
    dict(company='RealPact', category='Vertical AI for SMBs', contact='Erik Peterson', backup='Ranvir Deshmukh',
         linkedin='https://www.linkedin.com/in/erik-peterson-mn/', status='Verified', batch=1,
         subject='Every brokerage in one metro',
         research='Closed an oversubscribed pre-seed; founders previously built CourseMe, used by 90%+ of Dartmouth students and later acquired; carries a deal from first conversation to closing.',
         source='https://www.linkedin.com/in/erik-peterson-mn/',
         note='Hi Erik, from CourseMe at 90% of Dartmouth to an oversubscribed pre-seed for RealPact. Impressive run. Arsham from SpringBrand here. Would love to connect!',
         dm="Thanks for connecting, Erik!\n\nTaking a deal from first conversation to closing is a strong pitch for brokerages. SpringBrand's AI tools can help you reach them: brokerages by metro with broker-owner contacts, straight into your CRM, plus follow-up drafts. Most calls cost under a cent.\n\nPick a metro and I'll send you a free list. Which one?"),
    dict(company='Zaplar', category='Vertical AI for SMBs', contact='Douglas Solberg', backup='Axel Andersson Lingbert',
         linkedin='https://www.linkedin.com/in/douglas-solberg/', status='Verified', batch=1,
         subject='Independent hotels, one city at a time',
         research='Replaces PMS, MICE, POS and booking engine; agents handle voice bookings, RFPs and follow-ups while staff approve actions; raised $320K from Nyman Holding and Michael Ingelog on top of YC.',
         source='https://zaplar.com/blog/zaplar-accepted-into-y-combinator',
         note='Hi Douglas, one agentic system replacing PMS, MICE and POS, with staff approving every action, is a great design. Congrats on the Nyman round! Arsham, SpringBrand. Would love to connect.',
         dm="Thanks for connecting, Douglas!\n\nZaplar serves hotels and event venues, whose GMs and owners rarely answer cold outreach. SpringBrand's AI tools find independent hotels and venues by city with GM and owner contacts, and show which local keywords they compete on. Calls are under a cent, with no subscription.\n\nWant a free list for Stockholm, or any city you're expanding to?"),
    dict(company='Pango', category='Vertical AI for SMBs', contact='Lukasz Reszczynski', backup='Steve Rahimi',
         linkedin='https://www.linkedin.com/in/lukasz-reszczynski-bio/', status='Verified', batch=2,
         subject='Online brands buried in returns',
         research='AI agents run deliveries, tracking, returns, refunds and claims (about 99% without a human) across 100+ carriers; integrates with Shopify, WooCommerce and Magento; claims up to 30% fewer returns and 70% fewer delivery tickets; raised $550K.',
         source='https://yespress.io/pango-yc-s26',
         note='Hi Lukasz, AI agents running ~99% of deliveries, returns and claims across 100+ carriers is a big unlock for e-commerce. Arsham from SpringBrand. Would love to connect!',
         dm='Thanks for connecting, Lukasz!\n\nPango\'s best customers are online brands buried in returns and "where is my order" tickets. SpringBrand\'s AI tools can find e-commerce brands by category and size with their ops or CX leads, and show which ones shoppers complain about on Reddit and TikTok. Calls are under a cent, with no subscription.\n\nWant a free list of 25 brands to start?'),
    dict(company='Luca IQ', category='Vertical AI for SMBs', contact='Angelo Policicchio', backup='Akash Sadashivapeth',
         linkedin='https://www.linkedin.com/in/angelo-policicchio/', status='Verified', batch=2,
         subject='Every CPA firm in one metro',
         research='Intake to a review-ready 1040 in 30 minutes; passed IRS Assurance Testing and is now an authorized IRS e-file provider; saved a 12-person CPA firm 1,100 hours; Angelo is a CPA (ex-EY, FBI forensic accounting).',
         source='https://www.ycombinator.com/launches/SBo-luca-iq-an-api-for-u-s-tax-calculation-and-e-filing',
         note='Hi Angelo, intake to a review-ready 1040 in 30 minutes, and now an authorized IRS e-file provider. Congrats! Arsham from SpringBrand here. Would love to connect.',
         dm="Thanks for connecting, Angelo!\n\nWith results like 1,100 hours saved for a twelve-person firm, the hard part is getting in front of more CPA firms before tax season. SpringBrand's AI tools build lists of small and mid-size CPA firms by metro with partner contacts, and show which tax keywords firms compete on. Calls are under a cent.\n\nPick a metro and I'll send you a free list. Which one?"),
    dict(company='Bernard', category='Vertical AI for SMBs', contact='Dan Katzman', backup='David Goodfellow',
         linkedin='https://www.linkedin.com/in/dankatzman/', status='Verified', batch=2,
         subject='Appliance repair companies, one city at a time',
         research='AI handles phones, scheduling and dispatch for appliance repair companies; Pre-ID combines the appliance, symptoms, repair history and parts data so technicians arrive with the right parts; 9-person team in NYC.',
         source='https://bernardhq.com/',
         note='Hi Dan, Pre-ID sending technicians out with the right parts for a first-visit fix is such a practical wedge. Arsham from SpringBrand here. Would love to connect!',
         dm="Thanks for connecting, Dan!\n\nAppliance repair companies are local, owner-run and hard to reach at scale. SpringBrand's AI tools build lists of repair companies by city with owner contacts, show which local keywords they compete on, and make short demo videos of Pre-ID in action. Calls are under a cent, with no subscription.\n\nPick a city and I'll send you a free list. Where should I start?"),
    # --- AI-native service firms ---
    dict(company='Wingman Law', category='AI-native service firms', contact='Sunwoo Lee', backup='Mohini Tangri',
         linkedin='https://www.linkedin.com/in/lsunwoo/', status='Verified', batch=1,
         subject='Where PI firms get their clients',
         research='AI agents run the back office from intake through litigation so lawyers build stronger cases faster against insurers. Listed as YC F26 (not S26).',
         source='https://www.linkedin.com/in/lsunwoo/',
         note="Hi Sunwoo, AI agents running a PI firm's back office from intake through litigation is bold. Congrats on YC! Arsham from SpringBrand here. Would love to connect.",
         dm="Thanks for connecting, Sunwoo!\n\nWith intake handled by agents, Wingman's growth comes down to getting found by injured clients, and PI is one of the priciest search markets there is. SpringBrand shows where established PI firms get their traffic, which keywords you can win, and cost per lead on Google vs. Meta, at under a cent per call.\n\nWant a free breakdown of three PI firms in your market?"),
    dict(company='Billow AI Labs', category='AI-native service firms', contact='Philip Moniaga', backup='Joanathan McIntosh',
         linkedin='https://www.linkedin.com/in/philipmon/', status="Check: taken from Philip's Billow post; an older profile is at /in/philipmoniaga", batch=1,
         subject='Firms like your Series B–D partners',
         research="Phil built Bloomberg's financial data infrastructure and was CTO of a trading platform; Joan built and exited an accounting/ERP platform; already partnering with Series B–D companies worth $1B+ combined.",
         source='https://www.ycombinator.com/launches/SiY-billow-killing-deloitte-with-ai',
         note="Hi Philip, from Bloomberg's data infrastructure to an AI firm closing books for Series B–D companies. Billow is a great story. Arsham from SpringBrand. Would love to connect!",
         dm="Thanks for connecting, Philip!\n\nBillow's sweet spot looks like growth-stage finance teams. SpringBrand's AI tools can find more of them: Series B–D companies with their CFO or controller, pushed into your CRM, plus where Big-4 firms get their search traffic. Calls are under a cent, with no subscription.\n\nWant a free list of 25 companies that fit?"),
    dict(company='Donkey', category='AI-native service firms', contact='Benjamin Martindale', backup='Minghao (James) Tan',
         linkedin='https://www.linkedin.com/in/benjamin-martindale/', status='Verified', batch=2,
         subject='US importers paying three middlemen',
         research='Buys factory-direct in Asia, takes title and delivers duty-paid at a locked price; targets small importers paying 15–30% to each middleman; Benjamin advised Sany and Zoomlion on selling into Western markets; team in SF and Wuhan.',
         source='https://www.ycombinator.com/companies/donkey',
         note='Hi Benjamin, turning the shipping container into a cart for small importers is a great line. Love the Sany and Zoomlion background. Arsham, SpringBrand. Would love to connect!',
         dm="Thanks for connecting, Benjamin!\n\nDonkey's sweet spot is importers too big for single pallets but too small for a full container. SpringBrand's AI tools can find those US businesses by product category, with the owner or buyer's contact, and push them into your CRM. Calls are under a cent, with no subscription.\n\nWant a free list of 25 US importers in a category you're targeting?"),
    # --- Consumer & creator ---
    dict(company='Snap Poker', category='Consumer & creator', contact='Neel Gadde', backup='Dillon Mehta',
         linkedin='https://www.linkedin.com/in/neel-gadde-491880377/', status="Check: matches Neel's YC post, but the headline doesn't name Snap Poker", batch=1,
         subject='20 poker creators for Snap Poker',
         research='Real-money social poker app with a feed; players post hands as interactive reels with voiceover; zero rake, monetizes like a game rather than a casino.',
         source='https://playsnappoker.com/',
         note='Hi Neel, hands posted as interactive reels with voiceover, and zero rake. Snap Poker is a fresh take on online poker. Arsham from SpringBrand here. Would love to connect!',
         dm="Thanks for connecting, Neel!\n\nSince Snap Poker's feed is built for clips, poker creators are your best growth channel. SpringBrand's AI tools find poker creators with 20K–100K followers on TikTok, YouTube and X, and spot which hand formats are trending. Most calls cost under a cent.\n\nWant a free list of 20 creators who'd be a great fit to post their hands on Snap Poker?"),
    dict(company='Lumeria', category='Consumer & creator', contact='Anthea Guo', backup='Maryanne Alhallak',
         linkedin='https://www.linkedin.com/in/anthea-guo/', status='Verified', batch=1,
         subject="20 creators who'd love the Lumoscope",
         research='The Lumoscope clips onto a phone and sees skin in visible, polarized and UV light; Anthea held 150+ door-to-door conversations with dermatologists and patients; shipping Sep–Oct 2026.',
         source='https://www.linkedin.com/in/anthea-guo/',
         note='Hi Anthea, a clip-on camera that sees skin in visible, polarized and UV light, backed by 150+ derm and patient chats. Love Lumeria! Arsham, SpringBrand. Would love to connect.',
         dm="Thanks for connecting, Anthea!\n\nAs the Lumoscope ships, creator content could drive the next wave of orders. SpringBrand's AI tools find skincare and derm creators with 20K–100K followers, track which skin topics are trending, and turn product shots into short ads. Calls are under a cent, with no subscription.\n\nWant a free list of 20 creators who'd love the Lumoscope?"),
    dict(company='Audora', category='Consumer & creator', contact='Dhanush R.', backup='',
         linkedin='https://www.linkedin.com/in/dhanushrv/', status='Verified', batch=1,
         subject='BookTok, meet Audora',
         research="On-demand audiobooks with a unique voice per character (Dhanush's LinkedIn headline). Least public info of the 20.",
         source='https://in.linkedin.com/in/dhanushrv',
         note='Hi Dhanush, on-demand audiobooks with a distinct voice for every character is a lovely idea. BookTok is going to love Audora. Arsham from SpringBrand here. Would love to connect!',
         dm="Thanks for connecting, Dhanush!\n\nCharacter voices are made for short clips, and BookTok is where readers find their next book. SpringBrand's AI tools find book creators with 20K–100K followers on TikTok and Instagram, spot trending titles, and turn a scene into a short video with voiceover. Calls are under a cent.\n\nWant a free list of 20 BookTok creators, plus three clip ideas?"),
    dict(company='Tsenta', category='Consumer & creator', contact='Agnay Srivastava', backup='Pulkit Gupta',
         linkedin='https://www.linkedin.com/in/agnay/', status='Verified', batch=1,
         subject='20 career creators for Tsenta',
         research='Grew from 20K+ to 90K+ users in two months; launched an MCP server so AI agents can apply to jobs; 70%+ of paid users landed interviews; founders sent 3,000 applications themselves.',
         source='https://www.linkedin.com/in/agnay/',
         note='Hi Agnay, 90K+ users in two months, and an MCP server so agents can apply to jobs. Tsenta is moving fast. Arsham from SpringBrand here. Would love to connect!',
         dm="Thanks for connecting, Agnay!\n\nYou built Tsenta after sending 3,000 applications yourselves, and that story is perfect for career creators. SpringBrand's AI tools find career creators with 20K–100K followers on TikTok and LinkedIn, and track what job seekers complain about on Reddit. Calls are under a cent, with no subscription.\n\nWant a free list of 20 creators who'd be a great fit for Tsenta?"),
    dict(company='Gutgutgoose', category='Consumer & creator', contact='Leon Mojarrabi', backup='Anis Mihrshahi',
         linkedin='https://www.linkedin.com/in/leon-moj/', status='Verified', batch=2,
         subject='Gut-health creators for Gutgutgoose',
         research='Sequences a stool sample, builds a metabolic model of the gut and simulates which probiotic strains can colonize; raised $500K from YC; Leon started university at 14 and built a pharmacy doing $4M a year to fund the science.',
         source='https://www.ycombinator.com/launches/SAP-gutgutgoose-personalized-probiotics',
         note='Hi Leon, simulating which strains can actually colonize your gut is brilliant, and building a $4M pharmacy to fund it is bold. Arsham from SpringBrand. Would love to connect!',
         dm="Thanks for connecting, Leon!\n\nGut health is huge on TikTok and Instagram, and personalized probiotics are a story creators love to tell. SpringBrand's AI tools find gut-health and wellness creators with 20K–100K followers, track which topics are trending, and benchmark your pricing against other probiotic brands. Calls are under a cent.\n\nWant a free list of 20 creators who'd be a great fit for Gutgutgoose?"),
    dict(company='Wondering', category='Consumer & creator', contact='Cheng-Wei Hu', backup='Angelica Kosasih',
         linkedin='https://www.linkedin.com/in/cwhu/', status='Verified', batch=2,
         subject='20 education creators for Wondering',
         research='Turns any topic into a path of short visual lessons with podcasts and interactive exercises; 12,000+ people have completed 42,000+ lessons; Cheng-Wei is ex-NotebookLM, Angelica ex-Meta; they met at Cornell Tech.',
         source='https://x.com/HcwXd/status/2082874894308843939',
         note='Hi Cheng-Wei, 12,000 learners and 42,000 lessons already, built by an ex-NotebookLM engineer. Wondering is great. Arsham from SpringBrand here. Would love to connect!',
         dm='Thanks for connecting, Cheng-Wei!\n\n"Duolingo for anything" is made for short-form video. SpringBrand\'s AI tools find education creators with 20K–100K followers on TikTok, YouTube and Instagram, spot which topics people are curious about this week, and turn a lesson into a short clip with voiceover. Calls are under a cent.\n\nWant a free list of 20 creators who\'d be a great fit for Wondering?'),
]


def main():
    over = [(l["company"], len(l["note"])) for l in LEADS if len(l["note"]) > NOTE_LIMIT]
    assert not over, f"notes over {NOTE_LIMIT} chars: {over}"
    assert all(len(l["subject"]) <= 60 for l in LEADS), "subject too long"
    L = [f"# LinkedIn outreach ({len(LEADS)} companies)", "",
         "Batch 1: the first 20 companies. Batch 2: 10 more, marked *(batch 2)*.", "",
         "Two messages per contact: a **connection note** to send with the invite, and a **message after they accept**. "
         f"Notes are at most {NOTE_LIMIT} characters, so they fit on free and Premium accounts.", "",
         "**How to run it:** send each batch of invites in one day. When someone accepts, send the follow-up message the same day. "
         "If there's no reply after 4–5 days, like or comment on one of their posts, then send one short nudge: "
         "\"Hi {name}, just bumping this. Happy to send the free sample whenever it's useful.\" "
         "Log everything in the tracker CSV.", "",
         "**Research:** every note and follow-up cites specific, sourced facts about the company. "
         "Facts come from public web pages and LinkedIn as of September 2026, so skim the source before sending in case anything changed.", "",
         "**Subjects** belong to the follow-up message and only show on InMail or Sales Navigator. Regular DMs have no subject field.", "",
         "**Profiles:** ones marked *Check* were matched indirectly, so glance at the profile before sending. "
         "If a link is wrong, search LinkedIn for the name plus the company, or try the backup founder.", ""]
    cat = None
    for i, l in enumerate(LEADS, 1):
        if l["category"] != cat:
            cat = l["category"]; L += [f"## {cat}", ""]
        L += [f"### {i}. {l['company']}: {l['contact']}" + (" *(batch 2)*" if l["batch"] == 2 else ""), "",
              f"**LinkedIn:** {l['linkedin']} ({l['status']})" + (f" · backup: {l['backup']}" if l["backup"] else ""), "",
              f"**Research:** {l['research']} ([source]({l['source']}))", "",
              f"**1. Connection note** ({len(l['note'])} chars):", "", "> " + l["note"], "",
              f"**2. Message after they accept** (subject: *{l['subject']}*):", "",
              "> " + l["dm"].replace("\n\n", "\n>\n> "), ""]
    (ROOT / "docs/linkedin-outreach-day-1.md").write_text("\n".join(L))
    with open(ROOT / "private/linkedin-tracker.csv", "w", newline="", encoding="utf-8-sig") as f:
        w = csv.writer(f)
        w.writerow(["#", "Batch", "Company", "Category", "Contact", "LinkedIn profile", "Profile status", "Backup contact",
                    "Research", "Source", "Connection note", "Note chars", "Subject", "Message after accept",
                    "Invite sent", "Accepted", "Message sent", "Replied", "Next step"])
        for i, l in enumerate(LEADS, 1):
            w.writerow([i, l["batch"], l["company"], l["category"], l["contact"], l["linkedin"], l["status"], l["backup"],
                        l["research"], l["source"], l["note"], len(l["note"]), l["subject"], l["dm"], "", "", "", "", ""])
    lens = sorted(len(l["note"]) for l in LEADS)
    print(len(LEADS), f"contacts; notes {lens[0]}-{lens[-1]} chars")

if __name__ == "__main__":
    main()
